import Foundation

struct SettingsDefaultsState {
    var refreshFrequency: RefreshFrequency
    var launchAtLogin: Bool
    var debugMenuEnabled: Bool
    var debugDisableKeychainAccess: Bool
    var debugFileLoggingEnabled: Bool
    var debugLogLevelRaw: String?
    var debugLoadingPatternRaw: String?
    var debugKeepCLISessionsAlive: Bool
    var statusChecksEnabled: Bool
    var agentMeterBridgeEnabled: Bool
    var sessionQuotaNotificationsEnabled: Bool
    var quotaWarningNotificationsEnabled: Bool
    var quotaWarningThresholdsRaw: [Int]
    var quotaWarningSessionThresholdsRaw: [Int]
    var quotaWarningWeeklyThresholdsRaw: [Int]
    var quotaWarningSessionEnabled: Bool
    var quotaWarningWeeklyEnabled: Bool
    var quotaWarningSoundEnabled: Bool
    var quotaWarningMarkersVisible: Bool
    var weeklyProgressWorkDays: Int?
    var usageBarsShowUsed: Bool
    var resetTimesShowAbsolute: Bool
    var providerChangelogLinksEnabled: Bool
    var menuBarShowsBrandIconWithPercent: Bool
    var menuBarDisplayModeRaw: String?
    var kiroMenuBarDisplayModeRaw: String?
    var historicalTrackingEnabled: Bool
    var multiAccountMenuLayoutRaw: String
    var menuBarMetricPreferencesRaw: [String: String]
    var copilotBudgetExtrasEnabled: Bool
    var copilotIconSecondaryWindowIDRaw: String
    var costUsageEnabled: Bool
    var costUsageHistoryDays: Int
    var hidePersonalInfo: Bool
    var randomBlinkEnabled: Bool
    var confettiOnWeeklyLimitResetsEnabled: Bool
    var menuBarShowsHighestUsage: Bool
    var claudeOAuthKeychainPromptModeRaw: String?
    var claudeOAuthKeychainReadStrategyRaw: String?
    var claudeWebExtrasEnabledRaw: Bool
    var showOptionalCreditsAndExtraUsage: Bool
    var openAIWebAccessEnabled: Bool
    var openAIWebBatterySaverEnabled: Bool
    var providerStorageFootprintsEnabled: Bool
    var jetbrainsIDEBasePath: String
    var mergeIcons: Bool
    var switcherShowsIcons: Bool
    var mergedMenuLastSelectedWasOverview: Bool
    var mergedOverviewSelectedProvidersRaw: [String]
    var selectedMenuProviderRaw: String?
    var providerDetectionCompleted: Bool
    var appLanguageRaw: String?
    var terminalAppRaw: String?
}
